#!/bin/sh

cat <<EOF
This is a S2I base image for ForgeRock Identity Manager:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:
s2i build https://github.com/darkedges/s2i-forgerock-idm --context-dir=test/test-app/ darkedges/s2i-forgerock-idm:7.2.0 sample-app

You can then run the resulting image via:
docker run -p 8080:8080 sample-app
EOF
